name: usdol
description: Global Trace Protocol project.
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  equatable: ^2.0.5
  # providing a persistent store for simple data
  shared_preferences: ^2.2.2
  # Network info
  connectivity_plus: ^5.0.2
  # api client
  http_parser: ^4.0.2
  dio: ^5.4.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mime: ^1.0.4
  # Anim set
  flutter_spinkit: ^5.2.0
  # Loading shimmer
  shimmer: ^3.0.0
  another_flushbar: ^1.12.30
  # support svg data
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  #image picker
  image_picker: ^1.0.5
  flutter_image_compress: ^1.1.3
  # Location
  geolocator: 7.7.1
  geocoding: 2.0.2

  #mark
  tutorial_coach_mark: ^1.2.11
  #circle chart
  percent_indicator: ^4.2.3
  #date format
  jiffy: ^6.0.0
  #dot border
  dotted_border: ^2.1.0
  #file picker
  file_picker: ^5.5.0
  #QRcode scanner
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta
  permission_handler: ^10.4.5

  # pull up load and pull down refresh
  pull_to_refresh: ^2.0.0

  #file save
  open_filex: ^4.3.4
  #expandable
  expandable: ^5.0.1
  #range datetime
  calendar_date_picker2: ^0.5.3

  # detect keyboard shown
  flutter_keyboard_visibility: ^6.0.0

  #json Serializable
  json_serializable: ^6.7.1
  package_info_plus: 4.2.0 

  #device info
  device_info_plus: ^9.1.1

  #dynamic link
  flutter_branch_sdk: ^7.1.0

# dependency_overrides:
  # path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/country-data/
  fonts:
       - family: Sora
         fonts:
          - asset: assets/fonts/sora/Sora-Light.ttf
            weight: 300
          - asset: assets/fonts/sora/Sora-Regular.ttf
            weight: 400
          - asset: assets/fonts/sora/Sora-Medium.ttf
            weight: 500
          - asset: assets/fonts/sora/Sora-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/sora/Sora-Bold.ttf
            weight: 700
          - asset: assets/fonts/sora/Sora-ExtraBold.ttf
            weight: 800

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/appIcon.png"
  remove_alpha_ios: true

flutter_intl:
  enabled: true
